### ISSUE TITLE
Error in execution of RTCR in an DNAnexus applet 

### ISSUE THREAD

**Issue by adas83** [uubram/RTCR#12] opened 2021-02-05 19:38 UTC
Hello 

I am reaching out to you to ask for a resolution on an issue we have run into running the RTCR pipeline with a select set of samples on the DNAnexus cloud environment and the samples are not showing any clonotypes, even though we have seen clonotypes with these files in the past. We have tried troubleshooting it with running the applet in different environments and would like to make sure we can solve this issue. Would be great if someone from the support team could please contact us at adas@miodx.com and let us know how to resolve this issue. 

See error below from the execution :

Here is the environment we ran it with 
Our environment setup is Ubuntu 18.04, Python2.7, and Bowtie2.4.2. 

Here is the error log from the execution
mv data/analysis/alignments.sam.gz data/analysis/Samplename_human_alignments.sam.gz
++ dx upload data/analysis/Samplename_human_alignments.sam.gz --brief
+ alignments_samgz_fid=file-G07Z8F8066pyVJ9pKpQpK2bk
+ dx-jobutil-add-output alignments_samgz file-G07Z8F8066pyVJ9pKpQpK2bk --class=file
+ mv data/analysis/aln_stats.csv data/analysis/Samplename_human_aln_stats.csv
mv: cannot stat 'data/analysis/aln_stats.csv': No such file or directory

**Comment by uubram** [comment] 2021-02-05 20:25
I sent an e-mail, although I'd appreciate it if you'd reply to this thread. If the issue is resolved it may help others in the future (even if not, attempts at solving it might give ideas).

**Comment by adas83** [comment] 2021-02-05 21:15
Hi

Yes we received in MIODx, and have responded as well to that along with the
developers from DNAnexus cc'd to dig into the issue further.

Thanks
Ankita

**Comment by nishill** [comment] 2021-02-06 01:23
Hello, 

I am the Bioinformatician who was working on the RTCR DNAnexus application. Here's the error we're seeing,
```
Exception in thread Pipeline:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/rtcr-0.5.0-py2.7-linux-x86_64.egg/rtcr/pipeline.py", line 342, in run
    raise Exception(msg)
Exception: No clones found in alignments. Was the correct germline reference used?
```

It's happening at the end of the alignment stage after the `rtcr run` command is executed. Here is the log file,
```
2021-02-05 19:39:57,883 - MainProcess - Pipeline - INFO - Created temporary directory: "/tmp/tmpOkAHAD"
2021-02-05 19:39:57,884 - MainProcess - Pipeline - INFO - Running command: "/usr/bin/bowtie2-build /tmp/tmpOkAHAD/V_ref.fa /tmp/tmpOkAHAD/V_index"
2021-02-05 19:39:58,090 - MainProcess - Pipeline - INFO - Running command: "/usr/bin/bowtie2 --local -x /tmp/tmpOkAHAD/V_index - --phred33 --threads 18 -D 20 -R 3 -N 0 -i S,1,0.50 -L 8"
2021-02-05 19:39:58,093 - MainProcess - Pipeline - INFO - Running command: "/usr/bin/bowtie2-build /tmp/tmpOkAHAD/J_ref.fa /tmp/tmpOkAHAD/J_index"
2021-02-05 19:39:58,290 - MainProcess - Pipeline - INFO - Running command: "/usr/bin/bowtie2 --local -x /tmp/tmpOkAHAD/J_index - --phred33 --threads 18 -D 20 -R 3 -N 0 -i S,1,0.50 -L 6"
2021-02-05 20:07:33,129 - MainProcess - Pipeline - ERROR - No clones found in alignments. Was the correct germline reference used?
```

I see that the output SAM file is 4.8G so must have some alignments in it. Do you know what might be the issue?

**Comment by uubram** [comment] 2021-02-06 09:18
Having alignments without clones can happen if you have (overlapping) paired-end reads and did not merge them before running RTCR. Please let me know if you have paired-end reads and merging them before running RTCR solves your issue (also check out the section on paired-end reads in the [readme](https://github.com/uubram/RTCR#readme) ).

**Comment by nishill** [comment] 2021-02-08 16:41
I see, yes we do have paired-end reads and merging of them was done with pandaseq. Here's the full list of commands we used before the `rtcr run` step,
```
pandaseq -f ${R1_FASTQ_GZ} -r ${R2_FASTQ_GZ} -F -w merged.fastq
python n2zero.py -i merged.fastq -o merged_fixed.fastq -p 33
```

Do you see any potential issues with merging this way or could there be another cause of the error?

Thanks,
Nick

**Comment by uubram** [comment] 2021-02-08 17:18
Presuming you are using the merged_fixed.fastq as input, the steps look fine. Inability to retrieve a TCR from a sequence suggests that either the V or the J alignment failed. Can you check the alignment SAM file to see if there are only V or only J alignments for every sequence?

**Comment by nishill** [comment] 2021-02-09 00:24
That's correct, the merged_fixed.fastq is the input to `rtcr run`. I only see V alignments in the alignments.sam file, no J alignments. How should we proceed with the J alignments failing like this?

**Comment by uubram** [comment] 2021-02-09 10:03
Check that you are using the VJ reference sequences of the species that your sample is from. The VJ reference sequences appropriate for your sample can be selected using the '--species' argument to `rtcr run`.

If the J alignments are failing when the appropriate J reference sequences are used for alignment, then the input sequences do not contain a J gene or not enough bases of the J gene for alignment to succeed. In the latter case, it might be possible to compensate by adjusting the alignment settings of RTCR, either by switching aligners (please see the "Switching aligners" section in the [readme](https://github.com/uubram/RTCR)) or by updating the J alignment settings to bowtie2 using `rtcr Config Aligner.args_align_j` (see [bowtie2 manual](http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml) for an explanation of the arguments).

As a sanity check, please check a few input sequences (that had a successful V alignment) to see if [V-QUEST](http://www.imgt.org/IMGT_vquest/analysis) is able to find a CDR3.

**Comment by nishill** [comment] 2021-02-12 01:23
Thanks for providing these detailed options for us. I can confirm that the FASTQ reads are from the same species as the germline reference used. I tried changing several of the bowtie2 parameters for the j alignment settings but haven't had success yet. I'm now thinking of trying a different aligner, is there one that accepts FASTQ reads through stdin that you would recommend as an alternative?

**Comment by uubram** [comment] 2021-02-12 10:19
Before switching aligners, it is important to figure out if your input sequences to RTCR cover (part of) the J gene. There are multiple ways to determine this, with varying degrees of precision. I suggested previously to input a few sequences into [V-QUEST](http://www.imgt.org/IMGT_vquest/analysis), but you could also use [IgBlast](https://www.ncbi.nlm.nih.gov/igblast/) for example.

**Comment by nishill** [comment] 2021-02-12 23:43
Makes sense, we ran this sample's FASTQs through MIXCR which identified some candidate clones with a strong majority only aligning to the V segments and few aligning to the J segments (albeit with better alignment scores to the V segments). I took the possible J segment clones and inputted them into IgBlast which was able to associate them with particular V genes but not J genes. When I input those same clone sequences into V-QUEST I get 'no results'. 

The consensus I'm arriving at from these results is that there is not enough J gene sequence data in the reads for either RTCR or MIXCR to really capture the J gene clones. That said, it's important that we can capture some J gene alignment data from RTCR for this sample, so if there are any other setting adjustments to bowtie2 or different aligners you can recommend it would be greatly appreciated. 

Thanks for all of your help,

**Comment by uubram** [comment] 2021-02-14 19:38
You're welcome.

I am not sure what other aligner to recommend. It sounds like it may not be possible to unambiguously assign a J gene for any of your input sequences. I'd double check that the merging process worked and that you're not actually working with only the forward reads for example.

**Comment by nishill** [comment] 2021-02-16 21:34
That's okay. I double checked the output reads from the merging step and they look fine to me. I agree that we probably won't be able to unambiguously assign J genes for the sequences in this dataset. So, I think the error message we received from RTCR was informative. We can go ahead and close this issue. 

Thanks again for your assistance and all the work you've done in providing this tool.

Best,
Nick

**Comment by uubram** [comment] 2021-02-16 21:48
You're welcome and thank you for the kind words.

**Closed as completed by uubram** 2021-02-16 21:48 UTC
