### ISSUE TITLE
ValueError: len(seq) < 1

### ISSUE THREAD

**Issue by aqzas** [uubram/RTCR#4] opened 2018-04-16 08:40 UTC
This error occur with some fastq files, what might be the causes ? 

Traceback (most recent call last):
  File "/home/chensy/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/chensy/.local/lib/python2.7/site-packages/rtcr-0.3.1b0-py2.7-linux-x86_64.egg/rtcr/pipeline.py", line 348, in run
    self._include_cysphe, self._clone_classname)
  File "/home/chensy/.local/lib/python2.7/site-packages/rtcr-0.3.1b0-py2.7-linux-x86_64.egg/rtcr/clone.py", line 538, in build_clone
    other = (nt_jnc, q_jnc, 1))
  File "/home/chensy/.local/lib/python2.7/site-packages/rtcr-0.3.1b0-py2.7-linux-x86_64.egg/rtcr/clone.py", line 170, in __init__
    super(AnnotatedClone, self).__init__(*args, **kwargs)
  File "/home/chensy/.local/lib/python2.7/site-packages/rtcr-0.3.1b0-py2.7-linux-x86_64.egg/rtcr/clone.py", line 53, in __init__
    self._cqs = ConsensusQSequence(other)
ValueError: len(seq) < 1

**Comment by uubram** [comment] 2018-04-16 14:42
The cause is that RTCR (version 0.3.1) throws an error when it encounters a
0-length junction, instead of dropping it. This issue has been resolved in
newer versions of RTCR (version 0.3.2 and up). I recommend using the latest
version of RTCR (version 0.4.3 as of this writing).

**Closed as completed** 2018-05-13 00:27 UTC
